fixtures:
  repositories:
    'openstacklib':
      repo: 'git://github.com/enovance/puppet-openstacklib'
      ref: 'c374bed10f8af6000601fa407ebaef0833e1999c'
    'cinder':
      repo: 'git://github.com/enovance/puppet-cinder'
      ref: '77092bbc333e6e5fb512e7c5e88ad979435a23fd'
    'keystone':
      repo: 'git://github.com/enovance/puppet-keystone.git'
      ref: 'e381349c1b838301dd730aa3cd146ecacc75aa7c'
    'nova':
      repo: 'git://github.com/enovance/puppet-nova.git'
      ref: 'ae171f93ed8dc60e6597ec03a7cfd7c7b70e65ed'
    'glance':
      repo: 'git://github.com/enovance/puppet-glance.git'
      ref: '78042d76c0854e16a55aaf05c03696d4d422e3c5'
    'horizon':
      repo: 'git://github.com/enovance/puppet-horizon'
      ref: '16b482ea21a70d8dd06ab4c98ac5a218399b0213'
    'swift':
      repo: 'git://github.com/enovance/puppet-swift'
      ref: '3ea00440361ff2452561d2cce808d938e39cce56'
    'neutron':
      repo: 'git://github.com/enovance/puppet-neutron'
      ref: '3445712b1818160899862e8cf114604cb946813f'
    'ceilometer':
      repo: 'git://github.com/enovance/puppet-ceilometer'
      ref: '957c2120d0ee0b9db08bfddcce996686ba61d97d'
    'heat':
      repo: 'git://github.com/enovance/puppet-heat'
      ref: 'a95a9435dcb5f4b24b2e53213fe05b5466b46d6a'
    'trove':
      repo: 'git://github.com/enovance/puppet-trove'
      ref: '7d9db32423b25dcc227ea6a6d43c90c63fde0d58'
    'apt':
      repo: 'git://github.com/enovance/puppetlabs-apt.git'
      ref: '9b001af8775c7231ea2656b7eb43d6141b536f49'
    'apache':
      repo: 'git://github.com/enovance/puppetlabs-apache.git'
      ref: '58682faf74cdfc6c8d921d2be9322368c8a96cf9'
    'ceph':
      repo: 'git://github.com/enovance/puppet-ceph.git'
      ref: '581f7380b7b2fdeef9d7147b13156567ecfde074'
    'concat':
      repo: 'git://github.com/enovance/puppet-concat.git'
      ref: '04356974f72b90a1d0f57346a00e95a717924e43'
    'corosync':
      repo: 'git://github.com/enovance/puppetlabs-corosync.git'
      ref: '79b61302b07fef30b65a42f3b55229616018aacf'
    'firewall':
      repo: 'git://github.com/enovance/puppetlabs-firewall.git'
      ref: '6540b31b0ca0727094ddf44436274436d2853d6d'
    'pacemaker':
      repo: 'git://github.com/enovance/puppet-pacemaker.git'
      ref: '56bbb3580bb7fa62bf57c2ed7a30b938e42b8cc3'
    'elasticsearch':
      repo: 'git://github.com/enovance/puppet-elasticsearch.git'
      ref: '6d08442e8382f0f47388d4185122992c2d73cd9b'
    'git':
      repo: 'git://github.com/enovance/puppetlabs-git.git'
      ref: '0df1f62130a7752c728efb7555f2b07ca178ee5b'
    'fluentd':
      repo: 'git://github.com/enovance/puppet-fluentd.git'
      ref: 'd073a97002c569d8bfc38ac814ee33ed2cb13ca6'
    'haproxy':
      repo: 'git://github.com/enovance/puppetlabs-haproxy.git'
      ref: 'fc1166f28d411dfd4f59d4bfd6936595c014a11b'
    'keepalived':
      repo: 'git://github.com/enovance/puppet-module-keepalived.git'
      ref: 'eb345b6d3b25106cbe166028f2b8dd9974a10230'
    'kibana3':
      repo: 'git://github.com/enovance/kibana3.git'
      ref: '64fb5f898a0f062ebf188e53ba613b3b13e9d829'
    'mongodb':
      repo: 'git://github.com/enovance/puppetlabs-mongodb.git'
      ref: 'e3cc9a0ea895f6e01801e4620799c66c2337b7ed'
    'mysql':
      repo: 'git://github.com/enovance/puppetlabs-mysql.git'
      ref: '8b814d4d2cb5786a15e8e37fb3b7444d5d5f0d3f'
    'rabbitmq':
      repo: 'git://github.com/enovance/puppetlabs-rabbitmq'
      ref: '25420cb3c26c9a8432ab519d43c094d614d4fec4'
    'memcached':
      repo: 'git://github.com/enovance/puppet-memcached'
      ref: 'd009260de3c7623003318555ec5ca61217ea3ca1'
    'ntp':
      repo: 'git://github.com/enovance/puppetlabs-ntp.git'
      ref: 'a6d78648f6876f551a93ce7109067fcd1793b59f'
    'sysctl':
      repo: 'git://github.com/enovance/puppet-sysctl.git'
      ref: '4a463384e844f51b270428643a5b8beb3628e854'
    'inifile':
      repo: 'git://github.com/enovance/puppetlabs-inifile'
      ref: 'ae23a4db97d2815ec305d0529912685f07746d3c'
    'vswitch':
      repo: 'git://github.com/enovance/puppet-vswitch'
      ref: '49dbaff15e8f017dbe365ebf08eb505472b695a1'
    'vcsrepo':
      repo: 'git://github.com/enovance/puppetlabs-vcsrepo.git'
      ref: '4592bfd59cd5d4795069798a14b483e16c98c1ff'
    'stdlib':
      repo: 'git://github.com/enovance/puppetlabs-stdlib.git'
      ref: '224b8f9a191f635b03ee900a9bf87bfdb0f1a6ed'
    'xinetd':
      repo: 'git://github.com/enovance/puppetlabs-xinetd.git'
      ref: '7557af0e418d1a587df04fe7d01322ff2473c32e'
    'rhnreg_ks':
      repo: 'git://github.com/enovance/puppet-rhnreg_ks.git'
      ref: '8fdc051992b44a09f39d3b510d7cd6db5ed5ff66'
    'dnsclient':
      repo: 'git://github.com/enovance/puppet-module-dnsclient.git'
      ref: '4158b30f4660623f98dcdbd1ce9b482556180b57'
    'boolean':
      repo: 'git://github.com/enovance/puppet-boolean.git'
      ref: '157011a4eaa27f1202a9d94335ee4876b26d377e'
    'kmod':
      repo: 'git://github.com/enovance/puppet-kmod.git'
      ref: 'accc40093e6f8ee9cc472e9eb6ba3bab4bad3a1f'
    'ssh':
      repo: 'git://github.com/enovance/puppet-ssh.git'
      ref: '10675c0d80511a8cdd514af67b695887fa97ec40'
    'rsyslog':
      repo: 'git://github.com/enovance/puppet-rsyslog.git'
      ref: '67c7c501b916ebd1a27a8a218d49602339526c4f'
    'rsync':
      repo: 'git://github.com/enovance/puppetlabs-rsync.git'
      ref: '7122983d89bf68bc4170415cc03212f6a8a4636e'
  symlinks:
    'cloud': '#{source_dir}'
